import { type RouteConfig, index, layout, prefix, route } from '@react-router/dev/routes';

export default [
  index('routes/index.tsx'),
  route('install', 'routes/install.tsx'),
  route('login', 'routes/login.tsx'),
  route('logout', 'routes/logout.tsx'),
  layout('routes/console.tsx', [
    route('dashboard', 'routes/dashboard.tsx'),
    route('automation', 'routes/automation.tsx'),
    route('academic', 'routes/academic.tsx'),
    route('students', 'routes/students.tsx'),
    route('staff', 'routes/staff.tsx'),
    route('import', 'routes/import.tsx'),
    route('timetable', 'routes/timetable.tsx'),
    route('syllabus', 'routes/syllabus.tsx'),
    route('calendar', 'routes/calendar.tsx'),
    route('website', 'routes/website.tsx'),
    route('attendance', 'routes/attendance.tsx'),
    route('diary', 'routes/diary.tsx'),
    route('chat', 'routes/chat.tsx'),
    route('exams', 'routes/exams.tsx'),
    route('fees', 'routes/fees.tsx'),
    route('accounts', 'routes/accounts.tsx'),
    route('hr', 'routes/hr.tsx'),
    route('admissions', 'routes/admissions.tsx'),
    route('operations', 'routes/operations.tsx'),
    route('learning', 'routes/learning.tsx'),
    route('community', 'routes/community.tsx'),
  ]),
  route('teach', 'routes/teach.tsx'),
  ...prefix('site', [
    index('routes/site.tsx', { id: 'site-home' }),
    route(':slug', 'routes/site.tsx', { id: 'site-page' }),
  ]),
  ...prefix('portal', [
    index('routes/portal.tsx'),
    route('child/:id', 'routes/portal-child.tsx'),
  ]),
] satisfies RouteConfig;
