import pg from 'pg';
import type { Db, DbConfig, Row } from '../types.js';
import { bind, crud, splitStatements, toPgPlaceholders } from '../sql.js';

// Keep the same wire format as the other engines: datetimes as 'YYYY-MM-DD HH:MM:SS' strings, numerics as numbers.
pg.types.setTypeParser(1114, (v: string) => v.slice(0, 19));           // timestamp
pg.types.setTypeParser(1184, (v: string) => new Date(v).toISOString().slice(0, 19).replace('T', ' ')); // timestamptz
pg.types.setTypeParser(1082, (v: string) => v);                        // date
pg.types.setTypeParser(1700, (v: string) => Number(v));                // numeric
pg.types.setTypeParser(20, (v: string) => Number(v));                  // int8

/** VPS/Docker engine. Same schema, generated by db/generate.mjs into db/postgres/schema.sql. */
export function openPostgres(cfg: DbConfig): Db {
  const pool = cfg.url
    ? new pg.Pool({ connectionString: cfg.url, max: cfg.poolSize ?? 8 })
    : new pg.Pool({ host: cfg.host ?? '127.0.0.1', port: cfg.port ?? 5432, database: cfg.database, user: cfg.user, password: cfg.password, max: cfg.poolSize ?? 8 });
  return makeDb(pool, null);
}

function makeDb(pool: pg.Pool, client: pg.PoolClient | null): Db {
  const ex = client ?? pool;
  const query = async <T = Row>(sql: string, params: unknown[] = []) => {
    const r = await ex.query(toPgPlaceholders(sql), params.map(p => bind(p as never, 'postgres')));
    return r.rows as T[];
  };
  const execute = async (sql: string, params: unknown[] = []) => {
    const r = await ex.query(toPgPlaceholders(sql), params.map(p => bind(p as never, 'postgres')));
    return { affectedRows: r.rowCount ?? 0 };
  };
  const base = crud('postgres', query, execute);
  const db: Db = {
    engine: 'postgres',
    raw: pool,
    query, execute, ...base,
    async script(sql, opts) {
      let ran = 0, skipped = 0;
      for (const st of splitStatements(sql)) {
        try { await ex.query(st); ran++; }
        catch (e) { if (opts?.ignore?.(e as Error, st)) { skipped++; continue; } throw new Error(`${(e as Error).message}\n  in: ${st.slice(0, 200)}`); }
      }
      return { ran, skipped };
    },
    async transaction(fn) {
      if (client) return fn(db);
      const c = await pool.connect();
      try { await c.query('BEGIN'); const r = await fn(makeDb(pool, c)); await c.query('COMMIT'); return r; }
      catch (e) { try { await c.query('ROLLBACK'); } catch { /* ignore */ } throw e; }
      finally { c.release(); }
    },
    async close() { if (!client) await pool.end(); },
  };
  return db;
}
