import pg from 'pg';
import type { Db, DbConfig, Row } from '../types.js';
import { bind, crud, ident, splitStatements, toPgPlaceholders } from '../sql.js';

// Keep the same wire format as the other engines: datetimes as 'YYYY-MM-DD HH:MM:SS' strings, numerics as numbers.
pg.types.setTypeParser(1114, (v: string) => v.slice(0, 19));           // timestamp
pg.types.setTypeParser(1184, (v: string) => new Date(v).toISOString().slice(0, 19).replace('T', ' ')); // timestamptz
pg.types.setTypeParser(1082, (v: string) => v);                        // date
pg.types.setTypeParser(1700, (v: string) => Number(v));                // numeric
pg.types.setTypeParser(20, (v: string) => Number(v));                  // int8

/** VPS/Docker engine. Same schema, generated by db/generate.mjs into db/postgres/schema.sql. */
export function openPostgres(cfg: DbConfig): Db {
  const pool = cfg.url
    ? new pg.Pool({ connectionString: cfg.url, max: cfg.poolSize ?? 8 })
    : new pg.Pool({ host: cfg.host ?? '127.0.0.1', port: cfg.port ?? 5432, database: cfg.database, user: cfg.user, password: cfg.password, max: cfg.poolSize ?? 8 });
  // a column default is written by the server's clock; ours is UTC, so the server's has to be too
  pool.on('connect', c => { void c.query("SET TIME ZONE 'UTC'"); });
  return makeDb(pool, null);
}

let spCounter = 0;

function makeDb(pool: pg.Pool, client: pg.PoolClient | null): Db {
  const ex = client ?? pool;
  // Without parameters use the simple protocol so multi-statement strings (e.g. "DROP SCHEMA …; CREATE SCHEMA …") work.
  const send = (sql: string, params: unknown[]) => params.length ? ex.query(toPgPlaceholders(sql), params.map(p => bind(p as never, 'postgres'))) : ex.query(sql);
  const query = async <T = Row>(sql: string, params: unknown[] = []) => {
    const r = await send(sql, params);
    return r.rows as T[];
  };
  const execute = async (sql: string, params: unknown[] = []) => {
    const r = await send(sql, params);
    return { affectedRows: r.rowCount ?? 0 };
  };
  const base = crud('postgres', query, execute);
  const db: Db = {
    engine: 'postgres',
    raw: pool,
    query, execute, ...base,
    quote: (n: string) => ident(n, 'postgres'),
    async tables() { return (await query<{ name: string }>(`SELECT tablename AS name FROM pg_tables WHERE schemaname = current_schema() ORDER BY tablename`)).map(r => r.name); },
    async script(sql, opts) {
      let ran = 0, skipped = 0;
      for (const st of splitStatements(sql)) {
        try { await ex.query(st); ran++; }
        catch (e) { if (opts?.ignore?.(e as Error, st)) { skipped++; continue; } throw new Error(`${(e as Error).message}\n  in: ${st.slice(0, 200)}`); }
      }
      return { ran, skipped };
    },
    async attempt(fn) {
      if (!client) return fn();
      const name = `sp_${(spCounter = (spCounter + 1) % 1_000_000)}`;
      await client.query(`SAVEPOINT ${name}`);
      try { const r = await fn(); await client.query(`RELEASE SAVEPOINT ${name}`); return r; }
      catch (e) { await client.query(`ROLLBACK TO SAVEPOINT ${name}`); throw e; }
    },
    async transaction(fn) {
      if (client) return fn(db);
      const c = await pool.connect();
      try { await c.query('BEGIN'); const r = await fn(makeDb(pool, c)); await c.query('COMMIT'); return r; }
      catch (e) { try { await c.query('ROLLBACK'); } catch { /* ignore */ } throw e; }
      finally { c.release(); }
    },
    async close() { if (!client) await pool.end(); },
  };
  return db;
}
