import type { Request, Response, Router } from 'express';
import { HttpError, type App } from '@pathshala/core';
import { z } from '@pathshala/schemas';

type Wrap = (fn: (req: Request, res: Response) => Promise<unknown>) => (req: Request, res: Response, next: (e?: unknown) => void) => void;
type User = { id: string; school_id: string; user_type: string };

const dateSchema = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'YYYY-MM-DD');
const money = z.coerce.number().min(0).max(100_000_000);
const qty = z.coerce.number().min(0).max(1_000_000);

/** Phase 7 API: library, transport, hostel, inventory and assets, front office and the helpdesk. */
export function mountPhase7(api: Router, app: App, wrap: Wrap, requirePerm: (req: Request, perm: string) => User, requireUser: (req: Request) => User) {
  const q = (req: Request, k: string) => (typeof req.query[k] === 'string' ? String(req.query[k]) : undefined);
  const today = () => new Date().toISOString().slice(0, 10);

  // ---------- library ----------
  api.get('/library/books', wrap(async req => { const u = requirePerm(req, 'library.view'); return app.library.books(u.school_id, { q: q(req, 'q'), categoryId: q(req, 'categoryId') }); }));
  api.post('/library/books', wrap(async req => { const u = requirePerm(req, 'library.create'); const b = z.object({ isbn: z.string().max(20).optional().nullable(), title: z.string().min(1).max(255), authors: z.array(z.string().max(120)).optional(), publisher: z.string().max(160).optional().nullable(), categoryId: z.string().optional().nullable(), price: money.optional().nullable(), pages: z.coerce.number().int().optional().nullable(), copies: z.coerce.number().int().min(0).max(500).optional() }).parse(req.body); return app.library.addBook(u.school_id, b); }));
  api.post('/library/books/import', wrap(async req => { const u = requirePerm(req, 'library.create'); const b = z.object({ rows: z.array(z.object({ title: z.string().min(1).max(255), isbn: z.string().max(20).optional().nullable(), authors: z.array(z.string().max(120)).optional(), price: money.optional().nullable(), copies: z.coerce.number().int().min(0).max(500).optional() })).max(2000) }).parse(req.body); return app.library.importBooks(u.school_id, b.rows); }));
  api.get('/library/members', wrap(async req => { const u = requirePerm(req, 'library.view'); return app.library.members(u.school_id); }));
  api.post('/library/members', wrap(async req => { const u = requirePerm(req, 'library.create'); const b = z.object({ memberType: z.enum(['student', 'staff', 'guardian']), studentId: z.string().optional().nullable(), staffId: z.string().optional().nullable(), maxBooks: z.coerce.number().int().min(1).max(20).optional(), loanDays: z.coerce.number().int().min(1).max(120).optional(), finePerDay: money.optional() }).parse(req.body); return { id: await app.library.enrolMember(u.school_id, b) }; }));
  api.get('/library/issues', wrap(async req => { const u = requirePerm(req, 'library.view'); return app.library.issues(u.school_id, { memberId: q(req, 'memberId'), status: q(req, 'status'), overdueOnly: q(req, 'overdue') === '1' }); }));
  api.post('/library/issues', wrap(async req => { const u = requirePerm(req, 'library.edit'); const b = z.object({ copyId: z.string().optional(), accessionNo: z.string().max(30).optional(), memberId: z.string(), days: z.coerce.number().int().min(1).max(120).optional() }).parse(req.body); return app.library.issue(u.school_id, { ...b, issuedBy: u.id }); }));
  api.post('/library/issues/:id/renew', wrap(async req => { const u = requirePerm(req, 'library.edit'); return app.library.renew(u.school_id, req.params.id as string); }));
  api.post('/library/return', wrap(async req => { const u = requirePerm(req, 'library.edit'); const b = z.object({ issueId: z.string().optional(), copyId: z.string().optional(), accessionNo: z.string().max(30).optional(), lost: z.coerce.boolean().optional(), waiveFine: z.coerce.boolean().optional() }).parse(req.body); return app.library.returnBook(u.school_id, { ...b, returnedTo: u.id, waivedBy: u.id }); }));
  api.post('/library/reservations', wrap(async req => { const u = requirePerm(req, 'library.edit'); const b = z.object({ bookId: z.string(), memberId: z.string() }).parse(req.body); return { id: await app.library.reserve(u.school_id, b.bookId, b.memberId) }; }));
  api.post('/library/reading-logs', wrap(async req => { const u = requirePerm(req, 'library.edit'); const b = z.object({ studentId: z.string(), bookId: z.string(), pagesRead: z.coerce.number().int().min(0).max(10000).optional(), finished: z.coerce.boolean().optional(), review: z.string().max(4000).optional().nullable(), rating: z.coerce.number().int().min(1).max(5).optional().nullable() }).parse(req.body); return { id: await app.library.logReading(u.school_id, b) }; }));
  api.get('/library/readers', wrap(async req => { const u = requirePerm(req, 'library.view'); return app.library.readingLeaders(u.school_id); }));

  // ---------- transport ----------
  api.get('/transport/vehicles', wrap(async req => { const u = requirePerm(req, 'transport.view'); return app.transport.vehicles(u.school_id); }));
  api.post('/transport/vehicles', wrap(async req => { const u = requirePerm(req, 'transport.create'); const b = z.object({ registrationNo: z.string().min(2).max(30), vehicleType: z.enum(['bus', 'microbus', 'van', 'car']).optional(), makeModel: z.string().max(80).optional().nullable(), capacity: z.coerce.number().int().min(1).max(120), driverId: z.string().optional().nullable(), helperId: z.string().optional().nullable(), gpsDeviceId: z.string().max(60).optional().nullable(), insuranceExpiry: dateSchema.optional().nullable(), fitnessExpiry: dateSchema.optional().nullable(), taxTokenExpiry: dateSchema.optional().nullable(), routePermitExpiry: dateSchema.optional().nullable() }).parse(req.body); return { id: await app.transport.addVehicle(u.school_id, b) }; }));
  api.get('/transport/routes', wrap(async req => { const u = requirePerm(req, 'transport.view'); return app.transport.routes(u.school_id); }));
  api.post('/transport/routes', wrap(async req => { const u = requirePerm(req, 'transport.create'); const b = z.object({ name: z.string().min(1).max(120), vehicleId: z.string().optional().nullable(), startPoint: z.string().max(120).optional().nullable(), endPoint: z.string().max(120).optional().nullable(), monthlyFee: money.optional(), stops: z.array(z.object({ name: z.string().min(1).max(120), sequence: z.coerce.number().int().optional(), latitude: z.coerce.number().optional().nullable(), longitude: z.coerce.number().optional().nullable(), geofenceM: z.coerce.number().int().min(50).max(2000).optional(), pickupTime: z.string().optional().nullable(), dropTime: z.string().optional().nullable(), feeOverride: money.optional().nullable() })).optional() }).parse(req.body); return { id: await app.transport.createRoute(u.school_id, b) }; }));
  api.get('/transport/routes/:id/stops', wrap(async req => { const u = requirePerm(req, 'transport.view'); return app.transport.stops(u.school_id, req.params.id as string); }));
  api.get('/transport/routes/:id/riders', wrap(async req => { const u = requirePerm(req, 'transport.view'); return app.transport.riders(u.school_id, req.params.id as string); }));
  api.post('/transport/assign', wrap(async req => { const u = requirePerm(req, 'transport.edit'); const b = z.object({ studentId: z.string(), academicYearId: z.string().optional(), routeId: z.string(), stopId: z.string(), tripType: z.enum(['pickup', 'drop', 'both']).optional(), startDate: dateSchema.optional() }).parse(req.body); const yearId = b.academicYearId ?? String((await app.academic.requireYear(u.school_id, null)).id); return app.transport.assignStudent(u.school_id, { ...b, academicYearId: yearId }); }));
  api.get('/transport/trips', wrap(async req => { const u = requirePerm(req, 'transport.view'); return app.transport.trips(u.school_id, q(req, 'date') ?? today()); }));
  api.post('/transport/trips', wrap(async req => { const u = requirePerm(req, 'transport.edit'); return app.transport.createTrips(u.school_id, (req.body?.date as string) ?? today()); }));
  api.post('/transport/trips/:id/start', wrap(async req => { const u = requirePerm(req, 'transport.edit'); const b = z.object({ checklist: z.record(z.string(), z.coerce.boolean()).optional() }).parse(req.body ?? {}); return app.transport.startTrip(u.school_id, req.params.id as string, b.checklist); }));
  api.post('/transport/trips/:id/end', wrap(async req => { const u = requirePerm(req, 'transport.edit'); return app.transport.endTrip(u.school_id, req.params.id as string); }));
  api.post('/transport/board', wrap(async req => { const u = requirePerm(req, 'transport.edit'); const b = z.object({ tripId: z.string(), studentId: z.string(), stopId: z.string().optional().nullable(), direction: z.enum(['board', 'alight']).optional(), source: z.enum(['rfid', 'helper_app', 'manual']).optional() }).parse(req.body); return app.transport.board(u.school_id, b); }));
  api.post('/transport/gps', wrap(async req => { const u = requirePerm(req, 'transport.edit'); const b = z.object({ vehicleId: z.string(), packets: z.array(z.object({ latitude: z.coerce.number().min(-90).max(90), longitude: z.coerce.number().min(-180).max(180), speedKmh: z.coerce.number().min(0).max(300).optional().nullable(), heading: z.coerce.number().int().optional().nullable(), recordedAt: z.string().optional() })).max(200) }).parse(req.body); return app.transport.ingestGps(u.school_id, b.vehicleId, b.packets); }));

  // ---------- hostel ----------
  api.get('/hostel', wrap(async req => { const u = requirePerm(req, 'hostel.view'); return { hostels: await app.hostel.hostels(u.school_id), residents: await app.hostel.residents(u.school_id, q(req, 'hostelId')) }; }));
  api.post('/hostel', wrap(async req => { const u = requirePerm(req, 'hostel.create'); const b = z.object({ name: z.string().min(1).max(120), hostelType: z.enum(['boys', 'girls', 'staff']), wardenId: z.string().optional().nullable(), curfewTime: z.string().optional().nullable(), rooms: z.array(z.object({ roomNo: z.string().max(20), capacity: z.coerce.number().int().min(1).max(40), monthlyFee: money.optional(), roomType: z.enum(['single', 'double', 'shared', 'dorm']).optional(), floor: z.string().max(10).optional().nullable() })).optional() }).parse(req.body); return { id: await app.hostel.createHostel(u.school_id, b) }; }));
  api.get('/hostel/:id/rooms', wrap(async req => { const u = requirePerm(req, 'hostel.view'); return { rooms: await app.hostel.rooms(u.school_id, req.params.id as string), vacantBeds: await app.hostel.vacantBeds(u.school_id, req.params.id as string) }; }));
  api.post('/hostel/allocations', wrap(async req => { const u = requirePerm(req, 'hostel.edit'); const b = z.object({ studentId: z.string(), bedId: z.string(), academicYearId: z.string().optional(), fromDate: dateSchema.optional(), monthlyFee: money.optional() }).parse(req.body); const yearId = b.academicYearId ?? String((await app.academic.requireYear(u.school_id, null)).id); return app.hostel.allocate(u.school_id, { ...b, academicYearId: yearId }); }));
  api.post('/hostel/allocations/:id/vacate', wrap(async req => { const u = requirePerm(req, 'hostel.edit'); return app.hostel.vacate(u.school_id, req.params.id as string, req.body?.toDate as string | undefined); }));
  api.get('/hostel/outpasses', wrap(async req => { const u = requirePerm(req, 'hostel.view'); return app.hostel.outpasses(u.school_id, { status: q(req, 'status'), hostelId: q(req, 'hostelId') }); }));
  api.post('/hostel/outpasses', wrap(async req => { const u = requirePerm(req, 'hostel.create'); const b = z.object({ studentId: z.string(), leaveFrom: z.string(), expectedReturn: z.string(), reason: z.string().min(2).max(200), destination: z.string().max(160).optional().nullable() }).parse(req.body); return { id: await app.hostel.applyOutpass(u.school_id, b) }; }));
  api.post('/hostel/outpasses/:id/approve', wrap(async req => { const u = requirePerm(req, 'hostel.approve'); return app.hostel.approveOutpass(u.school_id, req.params.id as string, u.id); }));
  api.post('/hostel/outpasses/:id/reject', wrap(async req => { const u = requirePerm(req, 'hostel.approve'); return app.hostel.rejectOutpass(u.school_id, req.params.id as string, req.body?.reason as string | undefined); }));
  api.post('/hostel/outpasses/scan', wrap(async req => { const u = requirePerm(req, 'hostel.edit'); const b = z.object({ qr: z.string().min(4).max(64) }).parse(req.body); return app.hostel.scanOutpass(u.school_id, b.qr); }));
  api.post('/hostel/roll-call', wrap(async req => { const u = requirePerm(req, 'hostel.edit'); const b = z.object({ hostelId: z.string(), onDate: dateSchema, call: z.enum(['morning', 'night']), marks: z.array(z.object({ studentId: z.string(), status: z.enum(['present', 'absent', 'on_outpass', 'sick']) })).max(500) }).parse(req.body); return app.hostel.rollCall(u.school_id, b.hostelId, b.onDate, b.call, b.marks, u.id); }));
  api.post('/hostel/:id/menu', wrap(async req => { const u = requirePerm(req, 'hostel.edit'); const b = z.object({ rows: z.array(z.object({ dayOfWeek: z.coerce.number().int().min(0).max(6), meal: z.enum(['breakfast', 'lunch', 'snack', 'dinner']), items: z.string().max(255) })).max(28) }).parse(req.body); return app.hostel.setMenu(u.school_id, req.params.id as string, b.rows); }));
  api.post('/hostel/:id/meals', wrap(async req => { const u = requirePerm(req, 'hostel.edit'); const b = z.object({ onDate: dateSchema, meal: z.enum(['breakfast', 'lunch', 'snack', 'dinner']), rows: z.array(z.object({ studentId: z.string(), taken: z.coerce.boolean().optional(), cost: money.optional() })).max(500) }).parse(req.body); return app.hostel.recordMeals(u.school_id, req.params.id as string, b.onDate, b.meal, b.rows); }));
  api.post('/hostel/mess/bill', wrap(async req => { const u = requirePerm(req, 'hostel.approve'); const b = z.object({ month: z.string().regex(/^\d{4}-\d{2}/, 'YYYY-MM').optional(), hostelId: z.string().optional().nullable() }).parse(req.body ?? {}); return app.hostel.billMeals(u.school_id, b); }));
  api.get('/hostel/mess/summary', wrap(async req => { const u = requirePerm(req, 'hostel.view'); const studentId = q(req, 'studentId'); if (!studentId) throw new HttpError(400, 'studentId required'); return app.hostel.mealSummary(u.school_id, studentId, q(req, 'month')); }));
  api.get('/hostel/:id/menu', wrap(async req => { const u = requirePerm(req, 'hostel.view'); return app.hostel.menu(u.school_id, req.params.id as string); }));
  api.post('/hostel/complaints', wrap(async req => { const u = requirePerm(req, 'hostel.edit'); const b = z.object({ hostelId: z.string(), studentId: z.string().optional().nullable(), category: z.enum(['maintenance', 'food', 'safety', 'cleanliness', 'other']), description: z.string().min(2).max(4000) }).parse(req.body); return { id: await app.hostel.complain(u.school_id, b) }; }));

  // ---------- inventory ----------
  api.get('/inventory/items', wrap(async req => { const u = requirePerm(req, 'inventory.view'); return { items: await app.inventory.items(u.school_id, q(req, 'storeId')), stores: await app.inventory.stores(u.school_id), categories: await app.inventory.categories(u.school_id) }; }));
  api.post('/inventory/items', wrap(async req => { const u = requirePerm(req, 'inventory.create'); const b = z.object({ categoryId: z.string(), sku: z.string().max(40).optional(), name: z.string().min(1).max(160), unit: z.string().max(20).optional(), reorderLevel: qty.optional(), reorderQty: qty.optional().nullable(), preferredVendorId: z.string().optional().nullable(), lastCost: money.optional().nullable() }).parse(req.body); return app.inventory.addItem(u.school_id, b); }));
  api.get('/inventory/stock', wrap(async req => { const u = requirePerm(req, 'inventory.view'); return app.inventory.stock(u.school_id, q(req, 'storeId')); }));
  api.post('/inventory/movements', wrap(async req => { const u = requirePerm(req, 'inventory.edit'); const b = z.object({ itemId: z.string(), storeId: z.string(), moveType: z.enum(['in', 'out', 'adjust', 'transfer', 'return', 'consume']), quantity: z.coerce.number().min(-1_000_000).max(1_000_000), unitCost: money.optional().nullable(), note: z.string().max(255).optional().nullable() }).parse(req.body); return app.inventory.move(u.school_id, { ...b, createdBy: u.id }); }));
  api.post('/inventory/requisitions', wrap(async req => { const u = requirePerm(req, 'inventory.create'); const b = z.object({ requestedBy: z.string(), departmentId: z.string().optional().nullable(), items: z.array(z.object({ itemId: z.string(), quantity: qty })).min(1).max(100), justification: z.string().max(2000).optional().nullable() }).parse(req.body); return app.inventory.requisition(u.school_id, b); }));
  api.post('/inventory/quotations', wrap(async req => { const u = requirePerm(req, 'inventory.create'); const b = z.object({ requisitionId: z.string().optional().nullable(), vendorId: z.string(), items: z.array(z.object({ itemId: z.string(), quantity: qty, unitCost: money })).min(1).max(100), validUntil: dateSchema.optional().nullable() }).parse(req.body); return app.inventory.addQuotation(u.school_id, b); }));
  api.post('/inventory/requisitions/:id/select', wrap(async req => { const u = requirePerm(req, 'inventory.approve'); const b = z.object({ quotationId: z.string().optional() }).parse(req.body ?? {}); return app.inventory.selectQuotation(u.school_id, req.params.id as string, b.quotationId); }));
  api.get('/inventory/purchase-orders', wrap(async req => { const u = requirePerm(req, 'inventory.view'); return app.inventory.purchaseOrders(u.school_id, q(req, 'status')); }));
  api.post('/inventory/purchase-orders', wrap(async req => { const u = requirePerm(req, 'inventory.create'); const b = z.object({ vendorId: z.string(), storeId: z.string(), lines: z.array(z.object({ itemId: z.string(), quantity: qty, unitCost: money })).min(1).max(200), expectedDate: dateSchema.optional().nullable() }).parse(req.body); return app.inventory.createPurchaseOrder(u.school_id, { ...b, createdBy: u.id }); }));
  api.get('/inventory/purchase-orders/:id', wrap(async req => { const u = requirePerm(req, 'inventory.view'); return app.inventory.purchaseOrder(u.school_id, req.params.id as string); }));
  api.post('/inventory/purchase-orders/:id/receive', wrap(async req => { const u = requirePerm(req, 'inventory.edit'); const b = z.object({ items: z.array(z.object({ itemId: z.string(), quantity: qty })).min(1).max(200) }).parse(req.body); return app.inventory.receive(u.school_id, req.params.id as string, b.items, u.id); }));
  api.post('/inventory/issues', wrap(async req => { const u = requirePerm(req, 'inventory.create'); const b = z.object({ requestedBy: z.string(), storeId: z.string(), items: z.array(z.object({ itemId: z.string(), quantity: qty })).min(1).max(100), purpose: z.string().max(160).optional().nullable() }).parse(req.body); return app.inventory.issueRequest(u.school_id, b); }));
  api.get('/inventory/assets', wrap(async req => { const u = requirePerm(req, 'inventory.view'); return app.inventory.assets(u.school_id, { status: q(req, 'status') }); }));
  api.post('/inventory/assets/:id/assign', wrap(async req => { const u = requirePerm(req, 'inventory.edit'); const b = z.object({ roomId: z.string().optional().nullable(), custodianStaffId: z.string().optional().nullable() }).parse(req.body); return { updated: await app.inventory.assignAsset(u.school_id, req.params.id as string, b) }; }));
  api.post('/inventory/assets/:id/service', wrap(async req => { const u = requirePerm(req, 'inventory.edit'); const b = z.object({ serviceDate: dateSchema.optional(), serviceType: z.enum(['preventive', 'repair', 'calibration', 'inspection']).optional(), cost: money.optional().nullable(), nextDueDate: dateSchema.optional().nullable(), notes: z.string().max(2000).optional().nullable() }).parse(req.body); return { id: await app.inventory.serviceAsset(u.school_id, { ...b, assetId: req.params.id as string }) }; }));
  api.post('/inventory/audit', wrap(async req => { const u = requirePerm(req, 'inventory.approve'); const b = z.object({ storeId: z.string(), counted: z.array(z.object({ itemId: z.string(), quantity: qty })).min(1).max(1000), name: z.string().max(120).optional() }).parse(req.body); return app.inventory.auditStock(u.school_id, b.storeId, b.counted, b.name); }));

  // ---------- front office ----------
  api.get('/frontoffice/visitors', wrap(async req => { const u = requirePerm(req, 'frontoffice.view'); return app.frontOffice.visitors(u.school_id, q(req, 'date') ?? today()); }));
  api.post('/frontoffice/visitors', wrap(async req => { const u = requirePerm(req, 'frontoffice.create'); const b = z.object({ visitorName: z.string().min(2).max(160), phone: z.string().max(20).optional().nullable(), idProof: z.string().max(60).optional().nullable(), purpose: z.enum(['admission', 'meeting', 'delivery', 'pickup', 'interview', 'vendor', 'other']).optional(), toMeetStaffId: z.string().optional().nullable(), studentId: z.string().optional().nullable() }).parse(req.body); return app.frontOffice.checkIn(u.school_id, { ...b, loggedBy: u.id }); }));
  api.post('/frontoffice/visitors/:id/out', wrap(async req => { const u = requirePerm(req, 'frontoffice.edit'); return app.frontOffice.checkOut(u.school_id, req.params.id as string); }));
  api.get('/frontoffice/gate-passes', wrap(async req => { const u = requirePerm(req, 'frontoffice.view'); return app.frontOffice.gatePasses(u.school_id, q(req, 'date') ?? today()); }));
  api.post('/frontoffice/gate-passes', wrap(async req => { const u = requirePerm(req, 'frontoffice.create'); const b = z.object({ personType: z.enum(['student', 'staff']), studentId: z.string().optional().nullable(), staffId: z.string().optional().nullable(), reason: z.string().min(2).max(160), pickedBy: z.string().max(160).optional().nullable(), pickerPhone: z.string().max(20).optional().nullable(), expectedIn: z.string().optional().nullable() }).parse(req.body); return app.frontOffice.gatePass(u.school_id, { ...b, approvedBy: u.id }); }));
  api.post('/frontoffice/gate-passes/:id/return', wrap(async req => { const u = requirePerm(req, 'frontoffice.edit'); return app.frontOffice.returnFromPass(u.school_id, req.params.id as string); }));
  api.get('/frontoffice/calls', wrap(async req => { const u = requirePerm(req, 'frontoffice.view'); return app.frontOffice.calls(u.school_id); }));
  api.post('/frontoffice/calls', wrap(async req => { const u = requirePerm(req, 'frontoffice.create'); const b = z.object({ direction: z.enum(['inbound', 'outbound']), callerName: z.string().max(160).optional().nullable(), phone: z.string().min(4).max(20), purpose: z.string().max(160).optional().nullable(), notes: z.string().max(4000).optional().nullable(), followUpAt: z.string().optional().nullable() }).parse(req.body); return { id: await app.frontOffice.logCall(u.school_id, { ...b, loggedBy: u.id }) }; }));
  api.get('/frontoffice/post', wrap(async req => { const u = requirePerm(req, 'frontoffice.view'); return app.frontOffice.post(u.school_id); }));
  api.post('/frontoffice/post', wrap(async req => { const u = requirePerm(req, 'frontoffice.create'); const b = z.object({ direction: z.enum(['dispatch', 'receive']), referenceNo: z.string().max(60).optional().nullable(), fromParty: z.string().max(160).optional().nullable(), toParty: z.string().max(160).optional().nullable(), subject: z.string().max(200).optional().nullable(), recordDate: dateSchema.optional() }).parse(req.body); return { id: await app.frontOffice.logPost(u.school_id, { ...b, loggedBy: u.id }) }; }));
  api.get('/frontoffice/complaints', wrap(async req => { const u = requirePerm(req, 'frontoffice.view'); return app.frontOffice.complaints(u.school_id, { status: q(req, 'status'), category: q(req, 'category'), overdueOnly: q(req, 'overdue') === '1' }); }));
  api.get('/frontoffice/complaints/:id', wrap(async req => { const u = requirePerm(req, 'frontoffice.view'); return app.frontOffice.complaint(u.school_id, req.params.id as string); }));
  api.post('/frontoffice/complaints', wrap(async req => { const u = requirePerm(req, 'frontoffice.create'); const b = z.object({ category: z.enum(['academic', 'fees', 'transport', 'hostel', 'staff_behaviour', 'facility', 'safety', 'it', 'other']), subject: z.string().min(2).max(200), description: z.string().min(2).max(8000), priority: z.enum(['low', 'normal', 'high', 'urgent']).optional(), studentId: z.string().optional().nullable(), complainantName: z.string().max(160).optional().nullable(), complainantPhone: z.string().max(20).optional().nullable() }).parse(req.body); return app.frontOffice.raiseComplaint(u.school_id, { ...b, complainantUserId: u.id }); }));
  api.post('/frontoffice/complaints/:id', wrap(async req => { const u = requirePerm(req, 'frontoffice.edit'); const b = z.object({ note: z.string().max(4000).optional(), isInternal: z.coerce.boolean().optional(), status: z.enum(['open', 'in_progress', 'resolved', 'closed', 'reopened']).optional(), resolution: z.string().max(4000).optional().nullable(), assignedTo: z.string().optional().nullable() }).parse(req.body); return app.frontOffice.updateComplaint(u.school_id, req.params.id as string, { ...b, byUserId: u.id }); }));
  api.get('/frontoffice/lost-found', wrap(async req => { const u = requirePerm(req, 'frontoffice.view'); return app.frontOffice.lostFound(u.school_id); }));
  api.post('/frontoffice/lost-found', wrap(async req => { const u = requirePerm(req, 'frontoffice.create'); const b = z.object({ description: z.string().min(2).max(200), location: z.string().max(120).optional().nullable() }).parse(req.body); return { id: await app.frontOffice.logFound(u.school_id, b) }; }));
  api.post('/frontoffice/lost-found/:id/claim', wrap(async req => { const u = requirePerm(req, 'frontoffice.edit'); const b = z.object({ claimedBy: z.string().min(2).max(160) }).parse(req.body); return app.frontOffice.claimFound(u.school_id, req.params.id as string, b.claimedBy); }));

  // ---------- portal: a guardian's own child ----------
  api.get('/portal/operations/:studentId', wrap(async req => {
    const u = requireUser(req);
    const guardian = await app.db.findOne<{ id: string }>('guardians', { school_id: u.school_id, user_id: u.id });
    if (!guardian || !(await app.db.findOne('student_guardians', { student_id: req.params.studentId as string, guardian_id: guardian.id }))) throw new HttpError(403, 'not your child');
    const member = await app.db.findOne<{ id: string }>('library_members', { school_id: u.school_id, student_id: req.params.studentId as string });
    const [books, transport, hostel, outpasses] = await Promise.all([
      member ? app.library.issues(u.school_id, { memberId: member.id }) : [],
      app.db.query(`SELECT t.*, r.name AS route_name, s.name AS stop_name FROM student_transport t JOIN transport_routes r ON r.id = t.route_id JOIN route_stops s ON s.id = t.stop_id WHERE t.student_id = ? AND t.status = 'active'`, [req.params.studentId as string]),
      app.db.query(`SELECT a.*, r.room_no, b.bed_no, h.name AS hostel_name FROM hostel_allocations a JOIN hostel_beds b ON b.id = a.bed_id JOIN hostel_rooms r ON r.id = b.room_id JOIN hostels h ON h.id = r.hostel_id WHERE a.student_id = ? AND a.status = 'active'`, [req.params.studentId as string]),
      app.db.findMany('hostel_outpasses', { student_id: req.params.studentId as string } as never, { orderBy: 'leave_from DESC', limit: 20 }),
    ]);
    return { books, transport, hostel, outpasses };
  }));
  api.post('/portal/outpasses/:id/consent', wrap(async req => {
    const u = requireUser(req);
    return app.hostel.guardianConsent(u.school_id, req.params.id as string, u.id);
  }));
}
