export type Locale = 'bn' | 'en';

const dict = {
  en: {
    'app.name': 'Pathshala',
    'nav.dashboard': 'Dashboard', 'nav.automation': 'Automation', 'nav.settings': 'Settings', 'nav.logout': 'Sign out',
    'login.title': 'Sign in', 'login.identifier': 'Phone, email or username', 'login.password': 'Password', 'login.submit': 'Sign in', 'login.otp': 'Sign in with a code instead', 'login.totp': 'Authenticator code', 'login.failed': 'Wrong phone/email or password',
    'install.title': 'Set up Pathshala', 'install.subtitle': 'One form. Everything else is automatic.', 'install.preparing': 'Preparing the database…', 'install.schema': 'Database schema', 'install.seeds': 'Default data', 'install.school': 'School & admin', 'install.selftest': 'Self-test', 'install.done': 'Finish',
    'install.schoolName': 'School name', 'install.schoolNameBn': 'School name (Bangla)', 'install.type': 'Institution type', 'install.adminName': 'Your name', 'install.adminPhone': 'Your mobile', 'install.adminEmail': 'Email (optional)', 'install.adminPassword': 'Password', 'install.create': 'Create school', 'install.runSelfTest': 'Run self-test', 'install.finish': 'Open dashboard', 'install.locale': 'Default language',
    'dash.welcome': 'Welcome', 'dash.students': 'Students', 'dash.openTasks': 'Open tasks', 'dash.pendingApprovals': 'Pending approvals', 'dash.automationRuns': 'Automation runs (24h)', 'dash.recent': 'Recent automation activity', 'dash.empty': 'Nothing has happened yet. When people or rules act, it shows here.',
    'auto.title': 'Automation', 'auto.purpose': 'What the system did on its own, and what it will do next.', 'auto.runs': 'Rule runs', 'auto.jobs': 'Background jobs', 'auto.scheduled': 'Scheduled jobs', 'auto.rules': 'Rules', 'auto.mode': 'Scheduler mode', 'auto.tick': 'Run due jobs now', 'auto.nextRun': 'Next run', 'auto.lastRun': 'Last run', 'auto.status': 'Status',
    'status.success': 'success', 'status.failed': 'failed', 'status.pending': 'pending', 'status.running': 'running', 'status.skipped': 'skipped', 'status.preview': 'preview', 'status.done': 'done',
    'lang.switch': 'বাংলা',
    'nav.academic': 'Academic', 'nav.students': 'Students', 'nav.staff': 'Staff', 'nav.import': 'Import', 'nav.timetable': 'Timetable', 'nav.syllabus': 'Syllabus', 'nav.calendar': 'Calendar', 'nav.website': 'Website',
    'common.yes': 'Yes', 'common.no': 'No', 'common.type': 'Type', 'common.description': 'Description', 'common.new': 'New', 'common.save': 'Save', 'common.cancel': 'Cancel', 'common.search': 'Search', 'common.actions': 'Actions', 'common.none': 'None', 'common.loading': 'Loading…', 'common.saved': 'Saved', 'common.year': 'Academic year', 'common.class': 'Class', 'common.section': 'Section', 'common.subject': 'Subject', 'common.name': 'Name', 'common.phone': 'Phone', 'common.status': 'Status', 'common.date': 'Date', 'common.download': 'Download',
    'acad.years': 'Years', 'acad.classes': 'Classes', 'acad.subjects': 'Subjects', 'acad.sections': 'Sections', 'acad.matrix': 'Class subjects', 'acad.periods': 'Periods', 'acad.rooms': 'Rooms', 'acad.newYear': 'New academic year', 'acad.setCurrent': 'Make current', 'acad.preset': 'Add default classes & subjects', 'acad.capacity': 'Capacity', 'acad.enrolled': 'Enrolled', 'acad.weeklyPeriods': 'Periods / week', 'acad.level': 'Level',
    'stu.title': 'Students', 'stu.new': 'Admit student', 'stu.admissionNo': 'Admission no', 'stu.roll': 'Roll', 'stu.guardian': 'Guardian', 'stu.dob': 'Date of birth', 'stu.gender': 'Gender', 'stu.firstName': 'First name', 'stu.lastName': 'Last name', 'stu.nameBn': 'Name (Bangla)', 'stu.guardianName': 'Guardian name', 'stu.guardianPhone': 'Guardian mobile', 'stu.relation': 'Relation', 'stu.siblings': 'Siblings', 'stu.profile': 'Student profile',
    'staff.title': 'Staff', 'staff.new': 'Add staff', 'staff.employeeNo': 'Employee no', 'staff.category': 'Category', 'staff.designation': 'Designation', 'staff.subjects': 'Subjects taught', 'staff.joinDate': 'Join date',
    'imp.title': 'Import students from Excel', 'imp.purpose': 'Upload the template; rows with problems come back in an error file you can fix and re-upload.', 'imp.template': 'Download template', 'imp.upload': 'Upload .xlsx', 'imp.running': 'Importing…', 'imp.done': 'Import finished', 'imp.valid': 'valid rows', 'imp.invalid': 'rows with problems', 'imp.errorFile': 'Download error file', 'imp.history': 'Previous imports',
    'tt.title': 'Timetable', 'tt.purpose': 'Generate a clash-free timetable, adjust by hand, publish for teachers and guardians.', 'tt.generate': 'Generate', 'tt.publish': 'Publish', 'tt.versions': 'Versions', 'tt.clashes': 'Clashes', 'tt.placed': 'placed', 'tt.unplaced': 'unplaced', 'tt.published': 'Published', 'tt.draft': 'Draft', 'tt.substitutions': 'Substitutions', 'tt.suggest': 'Suggest substitutes', 'tt.teacherAbsent': 'Absent teacher',
    'syl.title': 'Syllabus & lesson plans', 'syl.new': 'New syllabus', 'syl.units': 'Units', 'syl.progress': 'Progress', 'syl.plan': 'Plan a lesson', 'syl.taught': 'Mark taught', 'syl.topic': 'Topic',
    'cal.title': 'Calendar', 'cal.new': 'Add event', 'cal.weekend': 'Weekly off days', 'cal.holiday': 'Holiday',
    'web.title': 'Website', 'web.purpose': 'The school site guardians and applicants see. Notices you publish here also go to the portal.', 'web.pages': 'Pages', 'web.notices': 'Notices', 'web.enquiries': 'Admission enquiries', 'web.newNotice': 'Publish notice', 'web.view': 'View site',
    'portal.children': 'My children', 'portal.notices': 'Notices', 'portal.timetable': 'Timetable', 'portal.events': 'Upcoming', 'portal.classTeacher': 'Class teacher', 'portal.today': 'Today',
    'site.admission': 'Admission enquiry', 'site.studentName': 'Student name', 'site.guardianName': 'Guardian name', 'site.send': 'Send', 'site.sent': 'Thank you — the admissions desk will call you.', 'site.contact': 'Contact', 'site.message': 'Message', 'site.classApplying': 'Class applying for',
    'day.0': 'Sun', 'day.1': 'Mon', 'day.2': 'Tue', 'day.3': 'Wed', 'day.4': 'Thu', 'day.5': 'Fri', 'day.6': 'Sat',
    'nav.attendance': 'Attendance', 'nav.leave': 'Leave', 'nav.chat': 'Messages', 'nav.diary': 'Diary', 'nav.teach': 'My classes',
    'att.title': 'Attendance', 'att.purpose': 'Mark a section in seconds; guardians of absent students get an SMS at the cut-off.', 'att.present': 'Present', 'att.absent': 'Absent', 'att.late': 'Late', 'att.halfDay': 'Half day', 'att.excused': 'Excused', 'att.allPresent': 'All present', 'att.save': 'Save attendance', 'att.saved': 'Attendance saved', 'att.holiday': 'That day is a holiday', 'att.onLeave': 'on leave', 'att.devices': 'Devices', 'att.policies': 'Policies', 'att.cutoff': 'Auto-absent at', 'att.deviceKey': 'Device key (shown once)', 'att.autoAbsent': 'Run auto-absent now', 'att.pct': 'Attendance %', 'att.staff': 'Staff attendance', 'att.summary': 'Summary',
    'lv.title': 'Leave', 'lv.apply': 'Apply for leave', 'lv.type': 'Leave type', 'lv.from': 'From', 'lv.to': 'To', 'lv.reason': 'Reason', 'lv.approve': 'Approve', 'lv.reject': 'Reject', 'lv.days': 'Days', 'lv.applicant': 'Applicant',
    'chat.title': 'Messages', 'chat.send': 'Send', 'chat.write': 'Write a message…', 'chat.section': 'Section channel', 'chat.empty': 'No conversations yet', 'chat.direct': 'New message',
    'dia.title': 'Diary', 'dia.homework': 'Homework', 'dia.note': 'Note', 'dia.new': 'Add entry', 'dia.due': 'Due', 'dia.report': 'Daily report', 'dia.mood': 'Mood', 'dia.nap': 'Nap (minutes)', 'dia.meals': 'Meals', 'dia.notes': 'Notes', 'dia.send': 'Send to guardians', 'dia.remark': 'Teacher remark',
    'ptm.title': 'Parent–teacher meetings', 'ptm.slots': 'Slots', 'ptm.book': 'Book', 'ptm.booked': 'Booked', 'ptm.create': 'Open slots',
    'nav.exams': 'Exams',
    'dash.setUp': 'Finish setting up', 'dash.setUpHint': 'These are the things a school needs before it can run a day.', 'dash.health': 'System', 'dash.queue': 'Jobs waiting', 'dash.storage': 'Uploads', 'dash.memory': 'Memory', 'dash.lastBackup': 'Last backup', 'dash.never': 'never',
    'lrn.title': 'Learning & welfare', 'lrn.purpose': 'Courses and homework, live classes, behaviour and health, surveys and events — the parts of school that are not marks.', 'lrn.courses': 'Courses', 'lrn.course': 'Course', 'lrn.lessons': 'Lessons', 'lrn.students': 'Students', 'lrn.newCourse': 'New course', 'lrn.publish': 'Publish', 'lrn.enrolled': 'students enrolled', 'lrn.liveClasses': 'Live classes', 'lrn.newClass': 'Schedule a live class', 'lrn.join': 'Join', 'lrn.starts': 'Starts', 'lrn.minutes': 'Minutes', 'lrn.jitsiHint': 'a meeting link is created automatically; no account needed', 'lrn.assignments': 'Assignments', 'lrn.newAssignment': 'New assignment', 'lrn.due': 'Due', 'lrn.handedIn': 'Handed in', 'lrn.latePenalty': 'Late penalty %', 'lrn.classSubjectId': 'Class subject id', 'lrn.classSubjectHint': 'copy it from the academic page', 'lrn.welfare': 'Behaviour & welfare', 'lrn.incidents': 'Incidents', 'lrn.newIncident': 'Record an incident', 'lrn.category': 'Category', 'lrn.points': 'Points', 'lrn.severity': 'Severity', 'lrn.actions': 'Disciplinary actions', 'lrn.action': 'Action', 'lrn.proposedBy': 'Proposed', 'lrn.acknowledged': 'Guardian', 'lrn.pendingActions': 'Awaiting approval', 'lrn.engagement': 'Surveys & events', 'lrn.survey': 'Survey', 'lrn.newSurvey': 'New survey', 'lrn.questions': 'Questions', 'lrn.questionsHint': 'one per line; each is answered out of five', 'lrn.anonymous': 'Anonymous', 'lrn.ask': 'Ask everyone', 'lrn.asked': 'guardians asked', 'lrn.results': 'Results', 'lrn.responses': 'responses', 'lrn.events': 'Events', 'lrn.newEvent': 'New event', 'lrn.coming': 'Coming', 'lrn.tickets': 'Tickets', 'lrn.ticketLimit': 'Ticket limit', 'lrn.rsvp': 'Ask for RSVP', 'lrn.announce': 'Tell everyone', 'lrn.told': 'guardians told', 'lrn.houses': 'House points', 'nav.learning': 'Learning',
    'ops.title': 'Operations', 'ops.purpose': 'Library, buses, hostel, stores and the front desk: the parts of the day nobody should write down twice.', 'ops.library': 'Library', 'ops.transport': 'Transport', 'ops.hostel': 'Hostel', 'ops.inventory': 'Stores & assets', 'ops.frontOffice': 'Front office', 'ops.booksOut': 'Books out', 'ops.overdue': 'Overdue', 'ops.tripsToday': 'Trips today', 'ops.residents': 'Residents', 'ops.openTickets': 'Open tickets', 'ops.newBook': 'Add a book', 'ops.issueBook': 'Issue a book', 'ops.catalogue': 'Catalogue', 'ops.book': 'Book', 'ops.authors': 'Authors', 'ops.authorsHint': 'separate names with commas', 'ops.price': 'Price', 'ops.copies': 'Copies', 'ops.available': 'Available', 'ops.accession': 'Accession', 'ops.accessionHint': 'the number on the copy, or scan the barcode', 'ops.memberId': 'Member id', 'ops.borrower': 'Borrower', 'ops.due': 'Due', 'ops.fine': 'Fine', 'ops.return': 'Take back', 'ops.returned': 'Returned', 'ops.route': 'Route', 'ops.routes': 'Routes', 'ops.newRoute': 'New route', 'ops.vehicle': 'Vehicle', 'ops.stops': 'Stops', 'ops.stopsHint': 'stop names, separated by commas', 'ops.riders': 'Riders', 'ops.monthlyFee': 'Monthly fee', 'ops.pickupTime': 'Pickup time', 'ops.makeTrips': "Create today's trips", 'ops.start': 'Start', 'ops.onBoard': 'On board', 'ops.startTrip': 'Start', 'ops.endTrip': 'End trip', 'ops.tripEnded': 'Trip closed.', 'ops.stillOnBoard': 'child(ren) still marked on the bus, alerts sent', 'ops.newHostel': 'New hostel', 'ops.rooms': 'Rooms', 'ops.beds': 'Beds', 'ops.occupied': 'Occupied', 'ops.curfew': 'Curfew', 'ops.outpasses': 'Out-passes', 'ops.leaves': 'Leaves', 'ops.returns': 'Back by', 'ops.consent': 'Guardian', 'ops.given': 'Consented', 'ops.waiting': 'Waiting', 'ops.approve': 'Approve', 'ops.newItem': 'New item', 'ops.store': 'Store', 'ops.quantity': 'In stock', 'ops.reorderAt': 'Reorder at', 'ops.reorderQty': 'Reorder qty', 'ops.unit': 'Unit', 'ops.category': 'Category', 'ops.categoryHint': 'paste a category id from the stores list', 'ops.purchaseOrders': 'Purchase orders', 'ops.poNo': 'Order', 'ops.vendor': 'Vendor', 'ops.value': 'Value', 'ops.raisedBy': 'Raised', 'ops.automatic': 'By the system', 'ops.byHand': 'By hand', 'ops.checkIn': 'Check a visitor in', 'ops.checkOut': 'Check out', 'ops.badge': 'Badge', 'ops.purposeCol': 'Purpose', 'ops.toMeet': 'To meet', 'ops.in': 'In', 'ops.out': 'Out', 'ops.tickets': 'Helpdesk', 'ops.ticket': 'Ticket', 'ops.newTicket': 'New ticket', 'ops.subject': 'Subject', 'ops.priority': 'Priority', 'ops.dueBy': 'Due by', 'ops.resolve': 'Resolve', 'nav.operations': 'Operations',
    'adm.title': 'Admissions', 'adm.purpose': 'Campaign to enrolment: the form fee submits the application, the admission fee makes the child a student.', 'adm.newCampaign': 'New admission', 'adm.open': 'Open it', 'adm.opened': 'The admission is open; the form is live on the website.', 'adm.close': 'Close it', 'adm.closed': 'Closed to new applications.', 'adm.opens': 'Opens', 'adm.closes': 'Closes', 'adm.formFee': 'Form fee', 'adm.selection': 'Selection', 'adm.seats': 'Seats', 'adm.offerValidity': 'Offer valid (days)', 'adm.applications': 'Applications', 'adm.applicationNo': 'Application', 'adm.enquiries': 'Enquiries', 'adm.student': 'Student', 'adm.guardian': 'Guardian', 'adm.source': 'Source', 'adm.followUp': 'Follow up', 'adm.followUpLogged': 'Follow-up recorded.', 'adm.logCall': 'Log a call', 'adm.rank': 'Merit', 'adm.score': 'Score', 'adm.merit': 'Compute merit list', 'adm.meritQueued': 'The merit list is being computed.', 'adm.shortlisted': 'Shortlisted', 'adm.waitlisted': 'Waitlisted', 'adm.offers': 'Offers', 'adm.makeOffers': 'Send offers', 'adm.expires': 'Expires', 'adm.accepted': 'Accepted', 'adm.declined': 'Declined', 'adm.revoked': 'Expired', 'adm.waiting': 'Waiting', 'adm.letter': 'Offer letter', 'adm.enrol': 'Enrol', 'adm.enrolled': 'Enrolled', 'adm.newTest': 'New admission test', 'adm.venue': 'Venue',
    'doc.title': 'Documents', 'doc.request': 'Request a document', 'doc.requested': 'Requested; issue it once approved.', 'doc.type': 'Document', 'doc.for': 'For', 'doc.blockers': 'What is blocking it', 'doc.blocked': 'Blocked', 'doc.issue': 'Issue', 'doc.issued': 'Issued', 'doc.reason': 'Reason', 'doc.studentId': 'Student id', 'doc.studentIdHint': 'copy it from the students page', 'doc.idCards': 'ID cards', 'doc.printJobs': 'Print batches', 'doc.validFrom': 'Valid from', 'doc.validTo': 'Valid to', 'doc.verify': 'Verify a document', 'nav.admissions': 'Admissions',
    'hr.title': 'HR & payroll', 'hr.purpose': 'Salary structures, attendance-driven payroll, payslips and the bank file — journaled as it goes.', 'hr.draftRun': 'Draft payroll', 'hr.month': 'Month', 'hr.monthHint': 'the salary month; attendance and leave for that month are read automatically', 'hr.queued': 'Payroll is being calculated in the background.', 'hr.staff': 'Staff', 'hr.employeeNo': 'Employee', 'hr.category': 'Category', 'hr.gross': 'Gross', 'hr.deductions': 'Deductions', 'hr.tax': 'Tax', 'hr.net': 'Net pay', 'hr.workingDays': 'Working days', 'hr.lop': 'Loss of pay', 'hr.payslip': 'Payslip', 'hr.payslips': 'Payslips', 'hr.approve': 'Approve', 'hr.approvedMsg': 'Approved — payslips and the bank file are being prepared.', 'hr.pay': 'Mark paid', 'hr.paid': 'Paid', 'hr.bankFile': 'Bank file', 'hr.structures': 'Salary structures', 'hr.setStructure': 'Set salary structure', 'hr.basic': 'Basic', 'hr.mpo': 'MPO share', 'hr.mpoHint': 'the part the government pays; it is recognised as grant income', 'hr.noStructure': 'No structure', 'hr.effectiveFrom': 'Effective from', 'hr.bank': 'Bank', 'hr.accountNo': 'Account no', 'hr.branch': 'Branch', 'hr.loans': 'Loans & advances', 'hr.newLoan': 'New loan', 'hr.principal': 'Principal', 'hr.instalment': 'Monthly cut', 'hr.balance': 'Balance', 'hr.startsFrom': 'Starts from', 'hr.hiring': 'Hiring', 'hr.newPosting': 'New vacancy', 'hr.vacancies': 'Vacancies', 'hr.closes': 'Closes', 'hr.salaryRange': 'Salary range', 'hr.applicants': 'Applicants', 'hr.stage': 'Stage', 'hr.advance': 'Move on', 'hr.stageMoved': 'Applicant moved to the next stage.', 'hr.exits': 'Exits', 'hr.newExit': 'Record an exit', 'hr.lastDay': 'Last working day', 'hr.noticeDate': 'Notice date', 'hr.settle': 'Settle', 'hr.settled': 'Final settlement', 'nav.hr': 'HR & payroll',
    'ex.title': 'Exams & results', 'ex.purpose': 'Schedule, mark, verify, compute — then publish report cards to every guardian.', 'ex.new': 'New exam', 'ex.schedules': 'Subjects', 'ex.seatPlan': 'Seat plan', 'ex.buildSeats': 'Build seat plan', 'ex.marks': 'Marks', 'ex.enterMarks': 'Enter marks', 'ex.verify': 'Verify', 'ex.lock': 'Lock', 'ex.unlock': 'Unlock', 'ex.compute': 'Compute results', 'ex.publish': 'Publish', 'ex.results': 'Results', 'ex.gpa': 'GPA', 'ex.grade': 'Grade', 'ex.rank': 'Rank', 'ex.total': 'Total', 'ex.theory': 'Theory', 'ex.practical': 'Practical', 'ex.ca': 'CA', 'ex.absent': 'Absent', 'ex.fullMarks': 'Full marks', 'ex.passMarks': 'Pass marks', 'ex.eligible': 'Eligible', 'ex.ineligible': 'Not eligible', 'ex.reportCard': 'Report card', 'ex.published': 'Published', 'ex.pending': 'Marks pending', 'ex.promote': 'Promote students', 'ex.annual': 'Annual result', 'ex.questions': 'Question bank', 'ex.paper': 'Question paper',
    'nav.fees': 'Fees', 'nav.accounts': 'Accounts',
    'fee.title': 'Fees', 'fee.purpose': 'Bill a month in one click; every payment posts its own journal entry.', 'fee.structures': 'Fee structures', 'fee.invoices': 'Invoices', 'fee.payments': 'Payments', 'fee.dues': 'Outstanding', 'fee.discounts': 'Discounts', 'fee.collect': 'Take payment', 'fee.generate': 'Generate this month', 'fee.outstanding': 'Outstanding', 'fee.collected': 'Collected', 'fee.invoiceNo': 'Invoice', 'fee.amount': 'Amount', 'fee.paid': 'Paid', 'fee.balance': 'Balance', 'fee.due': 'Due date', 'fee.method': 'Method', 'fee.receipt': 'Receipt', 'fee.remind': 'Send reminders', 'fee.fines': 'Apply fines', 'fee.head': 'Fee head', 'fee.monthly': 'Monthly', 'fee.ledger': 'Ledger', 'fee.cashOpen': 'Open cash session', 'fee.cashClose': 'Close & count', 'fee.gateway': 'Payment gateway', 'fee.payOnline': 'Pay online', 'fee.batch': 'Invoice batches',
    'acc.title': 'Accounts', 'acc.purpose': 'The books write themselves: fees, payments and expenses post their own journals.', 'acc.trialBalance': 'Trial balance', 'acc.entries': 'Journal entries', 'acc.expenses': 'Expenses', 'acc.income': 'Income', 'acc.expense': 'Expense', 'acc.surplus': 'Surplus', 'acc.balanced': 'Balanced', 'acc.unbalanced': 'Not balanced', 'acc.newExpense': 'Record expense', 'acc.category': 'Category', 'acc.debit': 'Debit', 'acc.credit': 'Credit', 'acc.account': 'Account', 'acc.entryNo': 'Entry', 'acc.banks': 'Bank & cash', 'acc.budgets': 'Budgets',
    'teach.title': 'My classes', 'teach.today': "Today's classes", 'teach.markNow': 'Mark attendance', 'teach.week': 'This week', 'teach.mySections': 'My sections', 'teach.subs': 'Substitutions for me',
  },
  bn: {
    'app.name': 'পাঠশালা',
    'nav.dashboard': 'ড্যাশবোর্ড', 'nav.automation': 'অটোমেশন', 'nav.settings': 'সেটিংস', 'nav.logout': 'সাইন আউট',
    'login.title': 'সাইন ইন', 'login.identifier': 'মোবাইল, ইমেইল বা ইউজারনেম', 'login.password': 'পাসওয়ার্ড', 'login.submit': 'সাইন ইন', 'login.otp': 'কোড দিয়ে সাইন ইন করুন', 'login.totp': 'অথেনটিকেটর কোড', 'login.failed': 'মোবাইল/ইমেইল বা পাসওয়ার্ড ভুল',
    'install.title': 'পাঠশালা সেটআপ', 'install.subtitle': 'একটি ফর্ম। বাকি সব স্বয়ংক্রিয়।', 'install.preparing': 'ডেটাবেজ তৈরি হচ্ছে…', 'install.schema': 'ডেটাবেজ স্কিমা', 'install.seeds': 'ডিফল্ট ডেটা', 'install.school': 'স্কুল ও অ্যাডমিন', 'install.selftest': 'সেলফ-টেস্ট', 'install.done': 'শেষ',
    'install.schoolName': 'স্কুলের নাম', 'install.schoolNameBn': 'স্কুলের নাম (বাংলা)', 'install.type': 'প্রতিষ্ঠানের ধরন', 'install.adminName': 'আপনার নাম', 'install.adminPhone': 'আপনার মোবাইল', 'install.adminEmail': 'ইমেইল (ঐচ্ছিক)', 'install.adminPassword': 'পাসওয়ার্ড', 'install.create': 'স্কুল তৈরি করুন', 'install.runSelfTest': 'সেলফ-টেস্ট চালান', 'install.finish': 'ড্যাশবোর্ড খুলুন', 'install.locale': 'ডিফল্ট ভাষা',
    'dash.welcome': 'স্বাগতম', 'dash.students': 'শিক্ষার্থী', 'dash.openTasks': 'খোলা কাজ', 'dash.pendingApprovals': 'অনুমোদন বাকি', 'dash.automationRuns': 'অটোমেশন রান (২৪ ঘণ্টা)', 'dash.recent': 'সাম্প্রতিক অটোমেশন', 'dash.empty': 'এখনও কিছু ঘটেনি। কেউ বা কোনো রুল কাজ করলে এখানে দেখা যাবে।',
    'auto.title': 'অটোমেশন', 'auto.purpose': 'সিস্টেম নিজে কী করেছে, আর পরে কী করবে।', 'auto.runs': 'রুল রান', 'auto.jobs': 'ব্যাকগ্রাউন্ড জব', 'auto.scheduled': 'নির্ধারিত জব', 'auto.rules': 'রুল', 'auto.mode': 'শিডিউলার মোড', 'auto.tick': 'বকেয়া জব এখন চালান', 'auto.nextRun': 'পরবর্তী রান', 'auto.lastRun': 'শেষ রান', 'auto.status': 'অবস্থা',
    'status.success': 'সফল', 'status.failed': 'ব্যর্থ', 'status.pending': 'অপেক্ষমাণ', 'status.running': 'চলছে', 'status.skipped': 'বাদ', 'status.preview': 'প্রিভিউ', 'status.done': 'সম্পন্ন',
    'lang.switch': 'English',
    'nav.academic': 'একাডেমিক', 'nav.students': 'শিক্ষার্থী', 'nav.staff': 'স্টাফ', 'nav.import': 'ইমপোর্ট', 'nav.timetable': 'রুটিন', 'nav.syllabus': 'সিলেবাস', 'nav.calendar': 'ক্যালেন্ডার', 'nav.website': 'ওয়েবসাইট',
    'common.yes': 'হ্যাঁ', 'common.no': 'না', 'common.type': 'ধরন', 'common.description': 'বিবরণ', 'common.new': 'নতুন', 'common.save': 'সংরক্ষণ', 'common.cancel': 'বাতিল', 'common.search': 'খুঁজুন', 'common.actions': 'কাজ', 'common.none': 'নেই', 'common.loading': 'লোড হচ্ছে…', 'common.saved': 'সংরক্ষিত', 'common.year': 'শিক্ষাবর্ষ', 'common.class': 'শ্রেণি', 'common.section': 'শাখা', 'common.subject': 'বিষয়', 'common.name': 'নাম', 'common.phone': 'মোবাইল', 'common.status': 'অবস্থা', 'common.date': 'তারিখ', 'common.download': 'ডাউনলোড',
    'acad.years': 'শিক্ষাবর্ষ', 'acad.classes': 'শ্রেণি', 'acad.subjects': 'বিষয়', 'acad.sections': 'শাখা', 'acad.matrix': 'শ্রেণিভিত্তিক বিষয়', 'acad.periods': 'পিরিয়ড', 'acad.rooms': 'কক্ষ', 'acad.newYear': 'নতুন শিক্ষাবর্ষ', 'acad.setCurrent': 'চলতি করুন', 'acad.preset': 'ডিফল্ট শ্রেণি ও বিষয় যোগ করুন', 'acad.capacity': 'ধারণক্ষমতা', 'acad.enrolled': 'ভর্তি', 'acad.weeklyPeriods': 'সাপ্তাহিক পিরিয়ড', 'acad.level': 'স্তর',
    'stu.title': 'শিক্ষার্থী', 'stu.new': 'শিক্ষার্থী ভর্তি', 'stu.admissionNo': 'ভর্তি নং', 'stu.roll': 'রোল', 'stu.guardian': 'অভিভাবক', 'stu.dob': 'জন্ম তারিখ', 'stu.gender': 'লিঙ্গ', 'stu.firstName': 'নাম', 'stu.lastName': 'পদবি', 'stu.nameBn': 'নাম (বাংলা)', 'stu.guardianName': 'অভিভাবকের নাম', 'stu.guardianPhone': 'অভিভাবকের মোবাইল', 'stu.relation': 'সম্পর্ক', 'stu.siblings': 'ভাইবোন', 'stu.profile': 'শিক্ষার্থীর প্রোফাইল',
    'staff.title': 'স্টাফ', 'staff.new': 'স্টাফ যোগ', 'staff.employeeNo': 'কর্মী নং', 'staff.category': 'ধরন', 'staff.designation': 'পদবি', 'staff.subjects': 'পড়ান যে বিষয়', 'staff.joinDate': 'যোগদান',
    'imp.title': 'এক্সেল থেকে শিক্ষার্থী ইমপোর্ট', 'imp.purpose': 'টেমপ্লেট আপলোড করুন; সমস্যাযুক্ত সারি এরর ফাইলে ফেরত আসবে, ঠিক করে আবার আপলোড করুন।', 'imp.template': 'টেমপ্লেট ডাউনলোড', 'imp.upload': '.xlsx আপলোড', 'imp.running': 'ইমপোর্ট চলছে…', 'imp.done': 'ইমপোর্ট শেষ', 'imp.valid': 'সঠিক সারি', 'imp.invalid': 'সমস্যাযুক্ত সারি', 'imp.errorFile': 'এরর ফাইল ডাউনলোড', 'imp.history': 'আগের ইমপোর্ট',
    'tt.title': 'রুটিন', 'tt.purpose': 'ক্ল্যাশমুক্ত রুটিন তৈরি করুন, হাতে ঠিক করুন, শিক্ষক ও অভিভাবকের জন্য প্রকাশ করুন।', 'tt.generate': 'তৈরি করুন', 'tt.publish': 'প্রকাশ', 'tt.versions': 'সংস্করণ', 'tt.clashes': 'ক্ল্যাশ', 'tt.placed': 'বসানো', 'tt.unplaced': 'বাকি', 'tt.published': 'প্রকাশিত', 'tt.draft': 'খসড়া', 'tt.substitutions': 'বদলি শিক্ষক', 'tt.suggest': 'বদলি প্রস্তাব', 'tt.teacherAbsent': 'অনুপস্থিত শিক্ষক',
    'syl.title': 'সিলেবাস ও পাঠ পরিকল্পনা', 'syl.new': 'নতুন সিলেবাস', 'syl.units': 'অধ্যায়', 'syl.progress': 'অগ্রগতি', 'syl.plan': 'পাঠ পরিকল্পনা', 'syl.taught': 'পড়ানো হয়েছে', 'syl.topic': 'বিষয়বস্তু',
    'cal.title': 'ক্যালেন্ডার', 'cal.new': 'ইভেন্ট যোগ', 'cal.weekend': 'সাপ্তাহিক ছুটি', 'cal.holiday': 'ছুটি',
    'web.title': 'ওয়েবসাইট', 'web.purpose': 'অভিভাবক ও আবেদনকারীরা যে সাইট দেখে। এখানে প্রকাশিত নোটিশ পোর্টালেও যায়।', 'web.pages': 'পেজ', 'web.notices': 'নোটিশ', 'web.enquiries': 'ভর্তির খোঁজ', 'web.newNotice': 'নোটিশ প্রকাশ', 'web.view': 'সাইট দেখুন',
    'portal.children': 'আমার সন্তান', 'portal.notices': 'নোটিশ', 'portal.timetable': 'রুটিন', 'portal.events': 'আসছে', 'portal.classTeacher': 'শ্রেণি শিক্ষক', 'portal.today': 'আজ',
    'site.admission': 'ভর্তির খোঁজ', 'site.studentName': 'শিক্ষার্থীর নাম', 'site.guardianName': 'অভিভাবকের নাম', 'site.send': 'পাঠান', 'site.sent': 'ধন্যবাদ — ভর্তি ডেস্ক আপনাকে ফোন করবে।', 'site.contact': 'যোগাযোগ', 'site.message': 'বার্তা', 'site.classApplying': 'কোন শ্রেণিতে',
    'day.0': 'রবি', 'day.1': 'সোম', 'day.2': 'মঙ্গল', 'day.3': 'বুধ', 'day.4': 'বৃহঃ', 'day.5': 'শুক্র', 'day.6': 'শনি',
    'nav.attendance': 'উপস্থিতি', 'nav.leave': 'ছুটি', 'nav.chat': 'বার্তা', 'nav.diary': 'ডায়েরি', 'nav.teach': 'আমার ক্লাস',
    'att.title': 'উপস্থিতি', 'att.purpose': 'কয়েক সেকেন্ডে শাখার হাজিরা নিন; কাট-অফে অনুপস্থিতদের অভিভাবক এসএমএস পাবেন।', 'att.present': 'উপস্থিত', 'att.absent': 'অনুপস্থিত', 'att.late': 'দেরি', 'att.halfDay': 'অর্ধদিবস', 'att.excused': 'ছুটি', 'att.allPresent': 'সবাই উপস্থিত', 'att.save': 'হাজিরা সংরক্ষণ', 'att.saved': 'হাজিরা সংরক্ষিত', 'att.holiday': 'ঐ দিন ছুটি', 'att.onLeave': 'ছুটিতে', 'att.devices': 'ডিভাইস', 'att.policies': 'নীতি', 'att.cutoff': 'অটো-অনুপস্থিত সময়', 'att.deviceKey': 'ডিভাইস কী (একবারই দেখানো হবে)', 'att.autoAbsent': 'এখনই অটো-অনুপস্থিত চালান', 'att.pct': 'উপস্থিতি %', 'att.staff': 'স্টাফ হাজিরা', 'att.summary': 'সারসংক্ষেপ',
    'lv.title': 'ছুটি', 'lv.apply': 'ছুটির আবেদন', 'lv.type': 'ছুটির ধরন', 'lv.from': 'শুরু', 'lv.to': 'শেষ', 'lv.reason': 'কারণ', 'lv.approve': 'অনুমোদন', 'lv.reject': 'প্রত্যাখ্যান', 'lv.days': 'দিন', 'lv.applicant': 'আবেদনকারী',
    'chat.title': 'বার্তা', 'chat.send': 'পাঠান', 'chat.write': 'বার্তা লিখুন…', 'chat.section': 'শাখা চ্যানেল', 'chat.empty': 'কোনো কথোপকথন নেই', 'chat.direct': 'নতুন বার্তা',
    'dia.title': 'ডায়েরি', 'dia.homework': 'বাড়ির কাজ', 'dia.note': 'নোট', 'dia.new': 'এন্ট্রি যোগ', 'dia.due': 'জমার তারিখ', 'dia.report': 'দৈনিক রিপোর্ট', 'dia.mood': 'মেজাজ', 'dia.nap': 'ঘুম (মিনিট)', 'dia.meals': 'খাবার', 'dia.notes': 'নোট', 'dia.send': 'অভিভাবককে পাঠান', 'dia.remark': 'শিক্ষকের মন্তব্য',
    'ptm.title': 'অভিভাবক–শিক্ষক সভা', 'ptm.slots': 'স্লট', 'ptm.book': 'বুক করুন', 'ptm.booked': 'বুকড', 'ptm.create': 'স্লট খুলুন',
    'nav.exams': 'পরীক্ষা',
    'dash.setUp': 'সেটআপ শেষ করুন', 'dash.setUpHint': 'একটি দিন চালানোর আগে স্কুলের যা যা লাগবে।', 'dash.health': 'সিস্টেম', 'dash.queue': 'অপেক্ষমাণ কাজ', 'dash.storage': 'আপলোড', 'dash.memory': 'মেমরি', 'dash.lastBackup': 'শেষ ব্যাকআপ', 'dash.never': 'কখনো নয়',
    'lrn.title': 'শেখা ও কল্যাণ', 'lrn.purpose': 'কোর্স ও বাড়ির কাজ, লাইভ ক্লাস, আচরণ ও স্বাস্থ্য, জরিপ ও অনুষ্ঠান — স্কুলের যেসব দিক নম্বর নয়।', 'lrn.courses': 'কোর্স', 'lrn.course': 'কোর্স', 'lrn.lessons': 'পাঠ', 'lrn.students': 'শিক্ষার্থী', 'lrn.newCourse': 'নতুন কোর্স', 'lrn.publish': 'প্রকাশ', 'lrn.enrolled': 'শিক্ষার্থী যুক্ত', 'lrn.liveClasses': 'লাইভ ক্লাস', 'lrn.newClass': 'লাইভ ক্লাস নির্ধারণ', 'lrn.join': 'যোগ দিন', 'lrn.starts': 'শুরু', 'lrn.minutes': 'মিনিট', 'lrn.jitsiHint': 'মিটিং লিংক নিজেই তৈরি হয়, কোনো অ্যাকাউন্ট লাগে না', 'lrn.assignments': 'অ্যাসাইনমেন্ট', 'lrn.newAssignment': 'নতুন অ্যাসাইনমেন্ট', 'lrn.due': 'জমার সময়', 'lrn.handedIn': 'জমা হয়েছে', 'lrn.latePenalty': 'দেরির কর্তন %', 'lrn.classSubjectId': 'ক্লাস-সাবজেক্ট আইডি', 'lrn.classSubjectHint': 'একাডেমিক পাতা থেকে কপি করুন', 'lrn.welfare': 'আচরণ ও কল্যাণ', 'lrn.incidents': 'ঘটনা', 'lrn.newIncident': 'ঘটনা লিখুন', 'lrn.category': 'শ্রেণি', 'lrn.points': 'পয়েন্ট', 'lrn.severity': 'মাত্রা', 'lrn.actions': 'শাস্তিমূলক ব্যবস্থা', 'lrn.action': 'ব্যবস্থা', 'lrn.proposedBy': 'প্রস্তাব', 'lrn.acknowledged': 'অভিভাবক', 'lrn.pendingActions': 'অনুমোদনের অপেক্ষায়', 'lrn.engagement': 'জরিপ ও অনুষ্ঠান', 'lrn.survey': 'জরিপ', 'lrn.newSurvey': 'নতুন জরিপ', 'lrn.questions': 'প্রশ্ন', 'lrn.questionsHint': 'প্রতি লাইনে একটি; উত্তর পাঁচের মধ্যে', 'lrn.anonymous': 'নাম ছাড়া', 'lrn.ask': 'সবাইকে জিজ্ঞাসা', 'lrn.asked': 'অভিভাবককে পাঠানো হয়েছে', 'lrn.results': 'ফল', 'lrn.responses': 'উত্তর', 'lrn.events': 'অনুষ্ঠান', 'lrn.newEvent': 'নতুন অনুষ্ঠান', 'lrn.coming': 'আসছেন', 'lrn.tickets': 'টিকিট', 'lrn.ticketLimit': 'টিকিট সীমা', 'lrn.rsvp': 'উপস্থিতি জানতে চান', 'lrn.announce': 'সবাইকে জানান', 'lrn.told': 'অভিভাবককে জানানো হয়েছে', 'lrn.houses': 'হাউস পয়েন্ট', 'nav.learning': 'শেখা',
    'ops.title': 'পরিচালনা', 'ops.purpose': 'লাইব্রেরি, বাস, হোস্টেল, স্টোর ও অভ্যর্থনা — দিনের যেসব কাজ দুবার লিখতে হয় না।', 'ops.library': 'লাইব্রেরি', 'ops.transport': 'পরিবহন', 'ops.hostel': 'হোস্টেল', 'ops.inventory': 'স্টোর ও সম্পদ', 'ops.frontOffice': 'অভ্যর্থনা', 'ops.booksOut': 'ইস্যু করা বই', 'ops.overdue': 'মেয়াদোত্তীর্ণ', 'ops.tripsToday': 'আজকের ট্রিপ', 'ops.residents': 'আবাসিক', 'ops.openTickets': 'খোলা টিকিট', 'ops.newBook': 'বই যোগ', 'ops.issueBook': 'বই ইস্যু', 'ops.catalogue': 'ক্যাটালগ', 'ops.book': 'বই', 'ops.authors': 'লেখক', 'ops.authorsHint': 'কমা দিয়ে আলাদা করুন', 'ops.price': 'মূল্য', 'ops.copies': 'কপি', 'ops.available': 'আছে', 'ops.accession': 'অ্যাক্সেশন', 'ops.accessionHint': 'কপির নম্বর, বা বারকোড স্ক্যান করুন', 'ops.memberId': 'সদস্য আইডি', 'ops.borrower': 'গ্রহীতা', 'ops.due': 'ফেরতের তারিখ', 'ops.fine': 'জরিমানা', 'ops.return': 'ফেরত নিন', 'ops.returned': 'ফেরত হয়েছে', 'ops.route': 'রুট', 'ops.routes': 'রুট', 'ops.newRoute': 'নতুন রুট', 'ops.vehicle': 'গাড়ি', 'ops.stops': 'স্টপ', 'ops.stopsHint': 'স্টপের নাম, কমা দিয়ে', 'ops.riders': 'যাত্রী', 'ops.monthlyFee': 'মাসিক ফি', 'ops.pickupTime': 'পিকআপ সময়', 'ops.makeTrips': 'আজকের ট্রিপ তৈরি', 'ops.start': 'শুরু', 'ops.onBoard': 'বাসে', 'ops.startTrip': 'শুরু', 'ops.endTrip': 'ট্রিপ শেষ', 'ops.tripEnded': 'ট্রিপ শেষ হয়েছে।', 'ops.stillOnBoard': 'জন এখনও বাসে চিহ্নিত — সতর্কতা পাঠানো হয়েছে', 'ops.newHostel': 'নতুন হোস্টেল', 'ops.rooms': 'কক্ষ', 'ops.beds': 'সিট', 'ops.occupied': 'পূর্ণ', 'ops.curfew': 'কারফিউ', 'ops.outpasses': 'আউট-পাস', 'ops.leaves': 'বের হবে', 'ops.returns': 'ফিরবে', 'ops.consent': 'অভিভাবক', 'ops.given': 'সম্মতি', 'ops.waiting': 'অপেক্ষায়', 'ops.approve': 'অনুমোদন', 'ops.newItem': 'নতুন পণ্য', 'ops.store': 'স্টোর', 'ops.quantity': 'মজুদ', 'ops.reorderAt': 'পুনঃক্রয় সীমা', 'ops.reorderQty': 'পুনঃক্রয় পরিমাণ', 'ops.unit': 'একক', 'ops.category': 'শ্রেণি', 'ops.categoryHint': 'স্টোর তালিকা থেকে আইডি দিন', 'ops.purchaseOrders': 'ক্রয় আদেশ', 'ops.poNo': 'আদেশ', 'ops.vendor': 'সরবরাহকারী', 'ops.value': 'মূল্য', 'ops.raisedBy': 'তৈরি', 'ops.automatic': 'স্বয়ংক্রিয়', 'ops.byHand': 'হাতে', 'ops.checkIn': 'দর্শনার্থী এন্ট্রি', 'ops.checkOut': 'বাহির', 'ops.badge': 'ব্যাজ', 'ops.purposeCol': 'উদ্দেশ্য', 'ops.toMeet': 'সাক্ষাৎ', 'ops.in': 'প্রবেশ', 'ops.out': 'প্রস্থান', 'ops.tickets': 'হেল্পডেস্ক', 'ops.ticket': 'টিকিট', 'ops.newTicket': 'নতুন টিকিট', 'ops.subject': 'বিষয়', 'ops.priority': 'অগ্রাধিকার', 'ops.dueBy': 'সময়সীমা', 'ops.resolve': 'নিষ্পত্তি', 'nav.operations': 'পরিচালনা',
    'adm.title': 'ভর্তি', 'adm.purpose': 'প্রচার থেকে ভর্তি: ফরম ফি দিলে আবেদন জমা, ভর্তি ফি দিলে শিক্ষার্থী।', 'adm.newCampaign': 'নতুন ভর্তি', 'adm.open': 'চালু করুন', 'adm.opened': 'ভর্তি চালু; ওয়েবসাইটে ফরম দেখা যাচ্ছে।', 'adm.close': 'বন্ধ করুন', 'adm.closed': 'নতুন আবেদন বন্ধ।', 'adm.opens': 'শুরু', 'adm.closes': 'শেষ', 'adm.formFee': 'ফরম ফি', 'adm.selection': 'বাছাই', 'adm.seats': 'আসন', 'adm.offerValidity': 'অফারের মেয়াদ (দিন)', 'adm.applications': 'আবেদন', 'adm.applicationNo': 'আবেদন নম্বর', 'adm.enquiries': 'অনুসন্ধান', 'adm.student': 'শিক্ষার্থী', 'adm.guardian': 'অভিভাবক', 'adm.source': 'উৎস', 'adm.followUp': 'পরবর্তী যোগাযোগ', 'adm.followUpLogged': 'যোগাযোগ লেখা হয়েছে।', 'adm.logCall': 'কল লিখুন', 'adm.rank': 'মেধাক্রম', 'adm.score': 'নম্বর', 'adm.merit': 'মেধাতালিকা তৈরি', 'adm.meritQueued': 'মেধাতালিকা তৈরি হচ্ছে।', 'adm.shortlisted': 'নির্বাচিত', 'adm.waitlisted': 'অপেক্ষমাণ', 'adm.offers': 'অফার', 'adm.makeOffers': 'অফার পাঠান', 'adm.expires': 'মেয়াদ', 'adm.accepted': 'গৃহীত', 'adm.declined': 'প্রত্যাখ্যাত', 'adm.revoked': 'মেয়াদোত্তীর্ণ', 'adm.waiting': 'অপেক্ষায়', 'adm.letter': 'অফার লেটার', 'adm.enrol': 'ভর্তি করুন', 'adm.enrolled': 'ভর্তি হয়েছে', 'adm.newTest': 'নতুন ভর্তি পরীক্ষা', 'adm.venue': 'কেন্দ্র',
    'doc.title': 'নথিপত্র', 'doc.request': 'নথির আবেদন', 'doc.requested': 'আবেদন জমা; অনুমোদনের পর ইস্যু করুন।', 'doc.type': 'নথি', 'doc.for': 'কার জন্য', 'doc.blockers': 'কী আটকে আছে', 'doc.blocked': 'আটকে আছে', 'doc.issue': 'ইস্যু', 'doc.issued': 'ইস্যু হয়েছে', 'doc.reason': 'কারণ', 'doc.studentId': 'শিক্ষার্থী আইডি', 'doc.studentIdHint': 'শিক্ষার্থী পাতা থেকে কপি করুন', 'doc.idCards': 'আইডি কার্ড', 'doc.printJobs': 'প্রিন্ট ব্যাচ', 'doc.validFrom': 'কার্যকর', 'doc.validTo': 'মেয়াদ', 'doc.verify': 'নথি যাচাই', 'nav.admissions': 'ভর্তি',
    'hr.title': 'এইচআর ও বেতন', 'hr.purpose': 'বেতন কাঠামো, হাজিরা অনুযায়ী পে-রোল, পে-স্লিপ ও ব্যাংক ফাইল — হিসাব নিজেই লেখা হয়।', 'hr.draftRun': 'বেতন খসড়া', 'hr.month': 'মাস', 'hr.monthHint': 'যে মাসের বেতন; ওই মাসের হাজিরা ও ছুটি নিজেই পড়ে নেওয়া হয়', 'hr.queued': 'পে-রোল পেছনে হিসাব হচ্ছে।', 'hr.staff': 'কর্মী', 'hr.employeeNo': 'কর্মী নম্বর', 'hr.category': 'শ্রেণি', 'hr.gross': 'মোট বেতন', 'hr.deductions': 'কর্তন', 'hr.tax': 'কর', 'hr.net': 'প্রদেয়', 'hr.workingDays': 'কর্মদিবস', 'hr.lop': 'বিনা বেতনে', 'hr.payslip': 'পে-স্লিপ', 'hr.payslips': 'পে-স্লিপ', 'hr.approve': 'অনুমোদন', 'hr.approvedMsg': 'অনুমোদিত — পে-স্লিপ ও ব্যাংক ফাইল তৈরি হচ্ছে।', 'hr.pay': 'পরিশোধ', 'hr.paid': 'পরিশোধিত', 'hr.bankFile': 'ব্যাংক ফাইল', 'hr.structures': 'বেতন কাঠামো', 'hr.setStructure': 'বেতন কাঠামো দিন', 'hr.basic': 'মূল বেতন', 'hr.mpo': 'এমপিও অংশ', 'hr.mpoHint': 'সরকার যে অংশ দেয়; অনুদান আয় হিসেবে ধরা হয়', 'hr.noStructure': 'কাঠামো নেই', 'hr.effectiveFrom': 'কার্যকর', 'hr.bank': 'ব্যাংক', 'hr.accountNo': 'হিসাব নম্বর', 'hr.branch': 'শাখা', 'hr.loans': 'ঋণ ও অগ্রিম', 'hr.newLoan': 'নতুন ঋণ', 'hr.principal': 'মূল টাকা', 'hr.instalment': 'মাসিক কর্তন', 'hr.balance': 'বকেয়া', 'hr.startsFrom': 'শুরু', 'hr.hiring': 'নিয়োগ', 'hr.newPosting': 'নতুন পদ', 'hr.vacancies': 'পদ সংখ্যা', 'hr.closes': 'শেষ তারিখ', 'hr.salaryRange': 'বেতন পরিসর', 'hr.applicants': 'আবেদনকারী', 'hr.stage': 'ধাপ', 'hr.advance': 'পরবর্তী ধাপ', 'hr.stageMoved': 'আবেদনকারী পরবর্তী ধাপে গেছেন।', 'hr.exits': 'বিদায়', 'hr.newExit': 'বিদায় নথিভুক্ত', 'hr.lastDay': 'শেষ কর্মদিবস', 'hr.noticeDate': 'নোটিশের তারিখ', 'hr.settle': 'চূড়ান্ত হিসাব', 'hr.settled': 'চূড়ান্ত পরিশোধ', 'nav.hr': 'এইচআর',
    'ex.title': 'পরীক্ষা ও ফলাফল', 'ex.purpose': 'সময়সূচি, নম্বর, যাচাই, ফল — তারপর সব অভিভাবকের কাছে রিপোর্ট কার্ড।', 'ex.new': 'নতুন পরীক্ষা', 'ex.schedules': 'বিষয়', 'ex.seatPlan': 'আসন বিন্যাস', 'ex.buildSeats': 'আসন বিন্যাস তৈরি', 'ex.marks': 'নম্বর', 'ex.enterMarks': 'নম্বর দিন', 'ex.verify': 'যাচাই', 'ex.lock': 'লক', 'ex.unlock': 'আনলক', 'ex.compute': 'ফল গণনা', 'ex.publish': 'প্রকাশ', 'ex.results': 'ফলাফল', 'ex.gpa': 'জিপিএ', 'ex.grade': 'গ্রেড', 'ex.rank': 'মেধাক্রম', 'ex.total': 'মোট', 'ex.theory': 'তত্ত্বীয়', 'ex.practical': 'ব্যবহারিক', 'ex.ca': 'ধারাবাহিক', 'ex.absent': 'অনুপস্থিত', 'ex.fullMarks': 'পূর্ণমান', 'ex.passMarks': 'পাস নম্বর', 'ex.eligible': 'যোগ্য', 'ex.ineligible': 'অযোগ্য', 'ex.reportCard': 'রিপোর্ট কার্ড', 'ex.published': 'প্রকাশিত', 'ex.pending': 'নম্বর বাকি', 'ex.promote': 'শিক্ষার্থী উত্তীর্ণ করুন', 'ex.annual': 'বার্ষিক ফল', 'ex.questions': 'প্রশ্ন ব্যাংক', 'ex.paper': 'প্রশ্নপত্র',
    'nav.fees': 'ফি', 'nav.accounts': 'হিসাব',
    'fee.title': 'ফি', 'fee.purpose': 'এক ক্লিকে মাসের বিল; প্রতিটি পেমেন্ট নিজেই জার্নাল এন্ট্রি করে।', 'fee.structures': 'ফি কাঠামো', 'fee.invoices': 'ইনভয়েস', 'fee.payments': 'পেমেন্ট', 'fee.dues': 'বকেয়া', 'fee.discounts': 'ছাড়', 'fee.collect': 'পেমেন্ট নিন', 'fee.generate': 'এ মাসের বিল তৈরি', 'fee.outstanding': 'বকেয়া', 'fee.collected': 'আদায়', 'fee.invoiceNo': 'ইনভয়েস', 'fee.amount': 'পরিমাণ', 'fee.paid': 'পরিশোধিত', 'fee.balance': 'বাকি', 'fee.due': 'শেষ তারিখ', 'fee.method': 'মাধ্যম', 'fee.receipt': 'রসিদ', 'fee.remind': 'রিমাইন্ডার পাঠান', 'fee.fines': 'জরিমানা প্রয়োগ', 'fee.head': 'ফি খাত', 'fee.monthly': 'মাসিক', 'fee.ledger': 'খতিয়ান', 'fee.cashOpen': 'ক্যাশ সেশন শুরু', 'fee.cashClose': 'বন্ধ ও গণনা', 'fee.gateway': 'পেমেন্ট গেটওয়ে', 'fee.payOnline': 'অনলাইনে পরিশোধ', 'fee.batch': 'ইনভয়েস ব্যাচ',
    'acc.title': 'হিসাব', 'acc.purpose': 'খাতা নিজেই লেখে: ফি, পেমেন্ট ও খরচ নিজেরাই জার্নাল করে।', 'acc.trialBalance': 'রেওয়ামিল', 'acc.entries': 'জার্নাল এন্ট্রি', 'acc.expenses': 'খরচ', 'acc.income': 'আয়', 'acc.expense': 'ব্যয়', 'acc.surplus': 'উদ্বৃত্ত', 'acc.balanced': 'মিলেছে', 'acc.unbalanced': 'মেলেনি', 'acc.newExpense': 'খরচ লিপিবদ্ধ', 'acc.category': 'খাত', 'acc.debit': 'ডেবিট', 'acc.credit': 'ক্রেডিট', 'acc.account': 'হিসাব', 'acc.entryNo': 'এন্ট্রি', 'acc.banks': 'ব্যাংক ও নগদ', 'acc.budgets': 'বাজেট',
    'teach.title': 'আমার ক্লাস', 'teach.today': 'আজকের ক্লাস', 'teach.markNow': 'হাজিরা নিন', 'teach.week': 'এই সপ্তাহ', 'teach.mySections': 'আমার শাখা', 'teach.subs': 'আমার বদলি ক্লাস',
  },
} as const;

export type MessageKey = keyof typeof dict.en;

export function t(key: MessageKey, locale: Locale = 'bn', vars?: Record<string, string | number>): string {
  let s: string = (dict[locale] as Record<string, string>)[key] ?? dict.en[key] ?? key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.replace(new RegExp(`{${k}}`, 'g'), String(v));
  return s;
}
export const messages = dict;

const BN_DIGITS = ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'];
export function formatNumber(n: number | string, locale: Locale = 'bn', numerals: 'bn' | 'en' = locale): string {
  const s = typeof n === 'number' ? n.toLocaleString('en-IN') : String(n);
  return numerals === 'bn' ? s.replace(/\d/g, d => BN_DIGITS[Number(d)]) : s;
}
export function formatMoney(n: number, locale: Locale = 'bn', numerals: 'bn' | 'en' = locale): string {
  return '৳' + formatNumber(Math.round(n * 100) / 100, locale, numerals);
}
export function formatDate(d: Date | string | null | undefined, locale: Locale = 'bn', opts: Intl.DateTimeFormatOptions = { day: 'numeric', month: 'short', year: 'numeric' }): string {
  if (!d) return '—';
  const date = typeof d === 'string' ? new Date(d.includes('T') || d.endsWith('Z') ? d : d.replace(' ', 'T') + 'Z') : d;
  if (Number.isNaN(date.getTime())) return String(d);
  return new Intl.DateTimeFormat(locale === 'bn' ? 'bn-BD' : 'en-GB', { timeZone: 'Asia/Dhaka', ...opts }).format(date);
}
export function formatDateTime(d: Date | string | null | undefined, locale: Locale = 'bn'): string {
  return formatDate(d, locale, { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });
}
