#!/usr/bin/env node
/**
 * Generates typed Drizzle ORM tables from db/schema.json (itself generated from db/schema/*.def.mjs).
 *   node packages/db/scripts/gen-drizzle.mjs
 * Writes packages/db/src/schema/mysql.ts and packages/db/src/schema/sqlite.ts (postgres shares the
 * sqlite-core shapes through the same column names; a pg-core file is emitted too).
 * Do not edit the generated files by hand.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '../../..');
const model = JSON.parse(fs.readFileSync(path.join(root, 'db/schema.json'), 'utf8'));
const outDir = path.join(here, '../src/schema');
fs.mkdirSync(outDir, { recursive: true });

const camel = s => s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
const parseType = t => { const m = t.match(/^(\w+)(?:\((.*)\))?$/); return { base: m[1], args: m[2] ?? null }; };
const enumVals = args => args.split('|').map(s => `'${s.trim()}'`).join(', ');

const dialects = {
  mysql: {
    pkg: 'drizzle-orm/mysql-core', table: 'mysqlTable',
    imports: ['mysqlTable', 'char', 'varchar', 'text', 'longtext', 'int', 'bigint', 'smallint', 'tinyint', 'decimal', 'double', 'date', 'datetime', 'time', 'json', 'index', 'uniqueIndex'],
    col(c) {
      const { base, args } = parseType(c.type); const n = `'${c.name}'`;
      switch (base) {
        case 'ulid': return `char(${n}, { length: 26 })`;
        case 'str': return `varchar(${n}, { length: ${args || 255} })`;
        case 'text': return `text(${n})`; case 'long': return `longtext(${n})`;
        case 'int': return `int(${n})`; case 'big': return `bigint(${n}, { mode: 'number' })`; case 'small': return `smallint(${n})`;
        case 'bool': return `tinyint(${n})`;
        case 'money': return `decimal(${n}, { precision: 14, scale: 2, mode: 'number' })`; case 'pct': return `decimal(${n}, { precision: 5, scale: 2, mode: 'number' })`;
        case 'dec': { const [p, s] = args.split(','); return `decimal(${n}, { precision: ${p}, scale: ${s}, mode: 'number' })`; }
        case 'float': return `double(${n})`;
        case 'date': return `date(${n}, { mode: 'string' })`; case 'dt': return `datetime(${n}, { mode: 'string' })`; case 'time': return `time(${n})`;
        case 'json': return `json(${n})`;
        case 'enum': return `varchar(${n}, { length: 40, enum: [${enumVals(args)}] })`;
        default: throw new Error(`unknown type ${c.type}`);
      }
    },
  },
  sqlite: {
    pkg: 'drizzle-orm/sqlite-core', table: 'sqliteTable',
    imports: ['sqliteTable', 'text', 'integer', 'numeric', 'real', 'index', 'uniqueIndex'],
    col(c) {
      const { base, args } = parseType(c.type); const n = `'${c.name}'`;
      switch (base) {
        case 'int': case 'big': case 'small': return `integer(${n})`;
        case 'bool': return `integer(${n}, { mode: 'boolean' })`;
        case 'money': case 'pct': case 'dec': return `numeric(${n}, { mode: 'number' })`;
        case 'float': return `real(${n})`;
        case 'json': return `text(${n}, { mode: 'json' })`;
        case 'enum': return `text(${n}, { enum: [${enumVals(args)}] })`;
        default: return `text(${n})`;
      }
    },
  },
  postgres: {
    pkg: 'drizzle-orm/pg-core', table: 'pgTable',
    imports: ['pgTable', 'char', 'varchar', 'text', 'integer', 'bigint', 'smallint', 'boolean', 'numeric', 'doublePrecision', 'date', 'timestamp', 'time', 'jsonb', 'index', 'uniqueIndex'],
    col(c) {
      const { base, args } = parseType(c.type); const n = `'${c.name}'`;
      switch (base) {
        case 'ulid': return `char(${n}, { length: 26 })`;
        case 'str': return `varchar(${n}, { length: ${args || 255} })`;
        case 'text': case 'long': return `text(${n})`;
        case 'int': return `integer(${n})`; case 'big': return `bigint(${n}, { mode: 'number' })`; case 'small': return `smallint(${n})`;
        case 'bool': return `boolean(${n})`;
        case 'money': return `numeric(${n}, { precision: 14, scale: 2 })`; case 'pct': return `numeric(${n}, { precision: 5, scale: 2 })`;
        case 'dec': { const [p, s] = args.split(','); return `numeric(${n}, { precision: ${p}, scale: ${s} })`; }
        case 'float': return `doublePrecision(${n})`;
        case 'date': return `date(${n}, { mode: 'string' })`; case 'dt': return `timestamp(${n}, { mode: 'string', precision: 3 })`; case 'time': return `time(${n})`;
        case 'jsonb': case 'json': return `jsonb(${n})`;
        case 'enum': return `varchar(${n}, { length: 40, enum: [${enumVals(args)}] })`;
        default: throw new Error(`unknown type ${c.type}`);
      }
    },
  },
};

for (const [name, d] of Object.entries(dialects)) {
  let out = `// GENERATED by packages/db/scripts/gen-drizzle.mjs from db/schema.json — do not edit.\n// ${model.tables} tables · ${model.columns} columns · ${model.generated}\n/* eslint-disable */\nimport { ${d.imports.join(', ')} } from '${d.pkg}';\n\n`;
  const names = [];
  for (const mod of model.modules) {
    out += `// ============ ${mod.title} ============\n`;
    for (const t of mod.tables) {
      const varName = camel(t.name);
      names.push(varName);
      out += `/** ${t.desc.replace(/\*\//g, '* /')} */\nexport const ${varName} = ${d.table}('${t.name}', {\n`;
      for (const c of t.cols) {
        let expr = d.col(c);
        if (c.name === 'id') expr += '.primaryKey()';
        else if (c.req) expr += '.notNull()';
        out += `  ${camel(c.name)}: ${expr},\n`;
      }
      const idx = [];
      for (const u of t.unique) idx.push(`uniqueIndex('uq_${t.name}_${u.join('_')}'.slice(0, 63)).on(${u.map(c => `t.${camel(c)}`).join(', ')})`);
      for (const ix of t.index) idx.push(`index('ix_${t.name}_${ix.join('_')}'.slice(0, 63)).on(${ix.map(c => `t.${camel(c)}`).join(', ')})`);
      out += idx.length ? `}, (t) => [\n  ${idx.join(',\n  ')},\n]);\n\n` : `});\n\n`;
    }
  }
  out += `export const tableNames = [${names.map(n => "'" + n + "'").join(', ')}] as const;
`;
  fs.writeFileSync(path.join(outDir, `${name}.ts`), out);
  console.log(`wrote packages/db/src/schema/${name}.ts (${names.length} tables)`);
}
