import webpush from 'web-push';
import type { PushAdapter, PushPayload, PushSubscription } from './interfaces.js';

export interface WebPushOptions { publicKey?: string; privateKey?: string; subject?: string }

/** Web Push over VAPID — free, no vendor account. Keys are generated by the installer when missing. */
export class WebPush implements PushAdapter {
  readonly kind = 'webpush';
  private ok = false;
  constructor(private o: WebPushOptions) {
    if (o.publicKey && o.privateKey) { webpush.setVapidDetails(o.subject || 'mailto:admin@example.com', o.publicKey, o.privateKey); this.ok = true; }
  }
  static generateKeys() { const k = webpush.generateVAPIDKeys(); return { publicKey: k.publicKey, privateKey: k.privateKey }; }
  publicKey() { return this.ok ? this.o.publicKey! : null; }
  async send(sub: PushSubscription, payload: PushPayload) {
    if (!this.ok) throw new Error('web push not configured: VAPID_PUBLIC_KEY / VAPID_PRIVATE_KEY missing');
    const r = await webpush.sendNotification(sub, JSON.stringify(payload), { TTL: 3600 });
    return { statusCode: r.statusCode };
  }
}

/** Records pushes instead of sending (tests, installs without keys). */
export class LogPush implements PushAdapter {
  readonly kind = 'log';
  sent: { sub: PushSubscription; payload: PushPayload }[] = [];
  publicKey() { return null; }
  async send(sub: PushSubscription, payload: PushPayload) { this.sent.push({ sub, payload }); return { statusCode: 201 }; }
}
